import prowlarrDefault from '@/templates/emails/prowlarr-default.hbs?raw'

import type { EmailTemplateDefinition } from '../types'

export const prowlarrTemplates: EmailTemplateDefinition[] = [
  {
    id: 'prowlarr-test',
    name: 'Prowlarr - Test',
    description: 'Template for Prowlarr test notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: 'Test Indexer',
      eventType: 'Test',
      actionLabel: 'Test',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'N/A',
      message: 'This is a test notification from Prowlarr to verify webhook connectivity.',
      indexerDetailsJSON: JSON.stringify([]),
      releaseDetailsJSON: JSON.stringify([]),
    },
  },
  {
    id: 'prowlarr-grab',
    name: 'Prowlarr - Grab',
    description: 'Template for Prowlarr grab notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: 'Nyaa.si',
      eventType: 'Grab',
      actionLabel: 'Grab',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'N/A',
      message: '[New-raws] One Piece - 1151 [1080p] [WEB-DL].mkv grabbed by Sonarr from Nyaa.si',
      indexerDetails: '',
      releaseDetailsJSON: JSON.stringify([
        { label: 'Title', value: '[New-raws] One Piece - 1151 [1080p] [WEB-DL].mkv' },
        { label: 'Quality', value: '1080p WEB-DL' },
        { label: 'Indexer', value: 'Nyaa.si' },
        { label: 'Size', value: '1.2 GB' },
      ]),
    },
  },
  {
    id: 'prowlarr-indexerstatuschange',
    name: 'Prowlarr - Indexer Status Change',
    description: 'Template for Prowlarr indexer status change notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: 'RARBG',
      eventType: 'IndexerStatusChange',
      actionLabel: 'Indexer Status Change',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'Healthy → Unhealthy',
      message: 'Indexer is no longer responding to requests',
      indexerDetailsJSON: JSON.stringify([
        { label: 'Protocol', value: 'Torrent' },
        { label: 'Priority', value: '1' },
        { label: 'RSS', value: 'Enabled' },
        { label: 'Automatic Search', value: 'Enabled' },
      ]),
      releaseDetails: '',
    },
  },
  {
    id: 'prowlarr-indexerupdate',
    name: 'Prowlarr - Indexer Update',
    description: 'Template for Prowlarr indexer update notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: '1337x',
      eventType: 'IndexerUpdate',
      actionLabel: 'Indexer Update',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'N/A',
      message: 'Indexer configuration has been updated',
      indexerDetailsJSON: JSON.stringify([
        { label: 'Protocol', value: 'Torrent' },
        { label: 'Priority', value: '2' },
        { label: 'RSS', value: 'Enabled' },
        { label: 'Automatic Search', value: 'Enabled' },
        { label: 'Interactive Search', value: 'Enabled' },
      ]),
      releaseDetails: '',
    },
  },
  {
    id: 'prowlarr-indexerdelete',
    name: 'Prowlarr - Indexer Delete',
    description: 'Template for Prowlarr indexer delete notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: 'ThePirateBay',
      eventType: 'IndexerDelete',
      actionLabel: 'Indexer Delete',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'N/A',
      message: 'Indexer has been removed from Prowlarr',
      indexerDetailsJSON: JSON.stringify([
        { label: 'Protocol', value: 'Torrent' },
        { label: 'Priority', value: '3' },
      ]),
      releaseDetails: '',
    },
  },
  {
    id: 'prowlarr-indexeradded',
    name: 'Prowlarr - Indexer Added',
    description: 'Template for Prowlarr indexer added notifications',
    html: prowlarrDefault,
    variables: ['indexerName', 'eventType', 'actionLabel', 'instanceName', 'protocol', 'statusChange', 'message', 'indexerDetailsJSON', 'releaseDetailsJSON', 'applicationUrl'],
    defaultVariables: {
      indexerName: 'TorrentGalaxy',
      eventType: 'IndexerAdded',
      actionLabel: 'Indexer Added',
      instanceName: 'prowlarr-main',
      protocol: 'Torrent',
      statusChange: 'N/A',
      message: 'New indexer has been added to Prowlarr',
      indexerDetailsJSON: JSON.stringify([
        { label: 'Protocol', value: 'Torrent' },
        { label: 'Priority', value: '4' },
        { label: 'RSS', value: 'Enabled' },
        { label: 'Automatic Search', value: 'Enabled' },
        { label: 'Interactive Search', value: 'Enabled' },
      ]),
      releaseDetails: '',
    },
  },
]
