import radarrDefault from '@/templates/emails/radarr-default.hbs?raw'

import type { EmailTemplateDefinition } from '../types'

export const radarrTemplates: EmailTemplateDefinition[] = [
  {
    id: 'radarr-grab',
    name: 'Radarr - Grab',
    description: 'Template for Radarr grab notifications',
    html: radarrDefault,
    variables: ['movieTitle', 'eventType', 'actionLabel', 'year', 'instanceName', 'downloadClient', 'isUpgrade', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      movieTitle: 'Dune: Part Two',
      eventType: 'Grab',
      actionLabel: 'Grab',
      year: '2024',
      instanceName: 'radarr-uplink',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      releaseDetails:
        '<div class="stack-item">Quality: 2160p WEB-DL</div><div class="stack-item">Title: Dune.Part.Two.2024.2160p.WEB-DL.DDP5.1.HDR.HEVC</div><div class="stack-item">Indexer: RARBG</div><div class="stack-item">Size: 18.5 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=960&q=80',
      synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      detailUrl: 'https://www.themoviedb.org/movie/693134-dune-part-two',
    },
  },
  {
    id: 'radarr-download',
    name: 'Radarr - Download',
    description: 'Template for Radarr download complete notifications',
    html: radarrDefault,
    variables: ['movieTitle', 'eventType', 'actionLabel', 'year', 'instanceName', 'downloadClient', 'isUpgrade', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      movieTitle: 'Dune: Part Two',
      eventType: 'Download',
      actionLabel: 'Download Complete',
      year: '2024',
      instanceName: 'radarr-uplink',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      releaseDetails:
        '<div class="stack-item">Quality: 2160p WEB-DL Dolby Vision</div><div class="stack-item">Release Group: TERMiNAL</div><div class="stack-item">Size: 18.5 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=960&q=80',
      synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      detailUrl: 'https://www.themoviedb.org/movie/693134-dune-part-two',
    },
  },
  {
    id: 'radarr-upgrade',
    name: 'Radarr - Upgrade',
    description: 'Template for Radarr upgrade notifications',
    html: radarrDefault,
    variables: ['movieTitle', 'eventType', 'actionLabel', 'year', 'instanceName', 'downloadClient', 'isUpgrade', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      movieTitle: 'Dune: Part Two',
      eventType: 'Upgrade',
      actionLabel: 'Upgrade',
      year: '2024',
      instanceName: 'radarr-uplink',
      downloadClient: 'NZBGet · ArrAuto',
      isUpgrade: 'Yes',
      releaseDetails:
        '<div class="stack-item">Quality: 2160p REMUX HEVC HDR10+</div><div class="stack-item">Release Group: TERMiNAL</div><div class="stack-item">Size: 82.7 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=960&q=80',
      synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      detailUrl: 'https://www.themoviedb.org/movie/693134-dune-part-two',
    },
  },
  {
    id: 'radarr-moviedelete',
    name: 'Radarr - Movie Delete',
    description: 'Template for Radarr movie delete notifications',
    html: radarrDefault,
    variables: ['movieTitle', 'eventType', 'actionLabel', 'year', 'instanceName', 'downloadClient', 'isUpgrade', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      movieTitle: 'The Matrix',
      eventType: 'MovieDelete',
      actionLabel: 'Delete Movie',
      year: '1999',
      instanceName: 'radarr-uplink',
      downloadClient: '',
      isUpgrade: 'No',
      releaseDetails: '',
      coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
      detailUrl: 'https://www.themoviedb.org/movie/603-the-matrix',
    },
  },
  {
    id: 'radarr-moviefiledelete',
    name: 'Radarr - Movie File Delete',
    description: 'Template for Radarr movie file delete notifications',
    html: radarrDefault,
    variables: ['movieTitle', 'eventType', 'actionLabel', 'year', 'instanceName', 'downloadClient', 'isUpgrade', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      movieTitle: 'Inception',
      eventType: 'MovieFileDelete',
      actionLabel: 'Delete File',
      year: '2010',
      instanceName: 'radarr-uplink',
      downloadClient: '',
      isUpgrade: 'No',
      releaseDetails: '',
      coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
      detailUrl: 'https://www.themoviedb.org/movie/27205-inception',
    },
  },
]
