import sonarrDefault from '@/templates/emails/sonarr-default.html?raw'

import type { EmailTemplateDefinition } from '../types'

export const sonarrTemplates: EmailTemplateDefinition[] = [
  {
    id: 'sonarr-grab',
    name: 'Sonarr - Grab',
    description: 'Template for Sonarr grab notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'One Piece',
      eventType: 'Grab',
      actionLabel: 'Grab',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      episodeList: '<div class="stack-item">S01E1151 · Episode 1151 · 2025-01-19</div>',
      releaseDetails:
        '<div class="stack-item">Quality: 1080p WEB-DL</div><div class="stack-item">Title: [New-raws] One Piece - 1151 [1080p] [WEB-DL].mkv</div><div class="stack-item">Indexer: Nyaa.si</div><div class="stack-item">Size: 1.2 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Monkey D. Luffy and his pirate crew explore the Grand Line in search of the world's ultimate treasure.",
      detailUrl: 'https://www.thetvdb.com/series/one-piece',
    },
  },
  {
    id: 'sonarr-download',
    name: 'Sonarr - Download',
    description: 'Template for Sonarr download complete notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'The Last of Us',
      eventType: 'Download',
      actionLabel: 'Download Complete',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      episodeList: '<div class="stack-item">S02E05 · Endure and Survive · 2025-02-09</div><div class="stack-item">S02E06 · The Dam · 2025-02-16</div>',
      releaseDetails: '<div class="stack-item">Quality: 2160p WEB-DL Dolby Vision</div><div class="stack-item">Release Group: NTb</div><div class="stack-item">Size: 8.4 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Joel and Ellie arrive at the Colorado hospital, where the Fireflies' true plan is revealed, and the journey faces its most difficult choice.",
      detailUrl: 'https://www.thetvdb.com/series/the-last-of-us',
    },
  },
  {
    id: 'sonarr-upgrade',
    name: 'Sonarr - Upgrade',
    description: 'Template for Sonarr upgrade notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'The Last of Us',
      eventType: 'Upgrade',
      actionLabel: 'Upgrade',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'Yes',
      episodeList: '<div class="stack-item">S02E05 · Endure and Survive · 2025-02-09</div>',
      releaseDetails:
        '<div class="stack-item">Quality: 2160p REMUX HEVC HDR10+</div><div class="stack-item">Release Group: TERMiNAL</div><div class="stack-item">Size: 12.8 GB</div>',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Joel and Ellie arrive at the Colorado hospital, where the Fireflies' true plan is revealed, and the journey faces its most difficult choice.",
      detailUrl: 'https://www.thetvdb.com/series/the-last-of-us',
    },
  },
  {
    id: 'sonarr-rename',
    name: 'Sonarr - Rename',
    description: 'Template for Sonarr rename notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'Breaking Bad',
      eventType: 'Rename',
      actionLabel: 'Rename',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeList: '<div class="stack-item">S05E16 · Felina · 2013-09-29</div>',
      releaseDetails: '',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.',
      detailUrl: 'https://www.thetvdb.com/series/breaking-bad',
    },
  },
  {
    id: 'sonarr-episodefiledelete',
    name: 'Sonarr - Episode File Delete',
    description: 'Template for Sonarr episode file delete notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'Game of Thrones',
      eventType: 'EpisodeFileDelete',
      actionLabel: 'Delete File',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeList: '<div class="stack-item">S08E06 · The Iron Throne · 2019-05-19</div>',
      releaseDetails: '',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'Nine noble families fight for control over the lands of Westeros.',
      detailUrl: 'https://www.thetvdb.com/series/game-of-thrones',
    },
  },
  {
    id: 'sonarr-seriesdelete',
    name: 'Sonarr - Series Delete',
    description: 'Template for Sonarr series delete notifications',
    html: sonarrDefault,
    variables: ['seriesTitle', 'eventType', 'actionLabel', 'instanceName', 'downloadClient', 'isUpgrade', 'episodeList', 'releaseDetails', 'coverImage', 'synopsis', 'detailUrl'],
    defaultVariables: {
      seriesTitle: 'The Office',
      eventType: 'SeriesDelete',
      actionLabel: 'Delete Series',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeList: '',
      releaseDetails: '',
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A mockumentary on a group of typical office workers.',
      detailUrl: 'https://www.thetvdb.com/series/the-office',
    },
  },
]
