import sonarrDefault from '@/templates/emails/sonarr-default.hbs?raw'

import type { EmailTemplateDefinition } from '../types'

export const sonarrTemplates: EmailTemplateDefinition[] = [
  {
    id: 'sonarr-test',
    name: 'Sonarr - Test',
    description: 'Template for Sonarr test notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'Test Series',
      eventType: 'Test',
      actionLabel: 'Test',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([{ code: 'S01E01', name: 'Test Episode', airDate: '2024-01-01' }]),
      releaseDetailsJSON: JSON.stringify([]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'This is a test notification from Sonarr to verify webhook connectivity.',
      detailUrl: 'https://www.thetvdb.com',
    },
  },
  {
    id: 'sonarr-grab',
    name: 'Sonarr - Grab',
    description: 'Template for Sonarr grab notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'One Piece',
      eventType: 'Grab',
      actionLabel: 'Grab',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([{ code: 'S01E1151', name: 'Episode 1151', airDate: '2025-01-19' }]),
      releaseDetailsJSON: JSON.stringify([
        { label: 'Quality', value: '1080p WEB-DL' },
        { label: 'Title', value: '[New-raws] One Piece - 1151 [1080p] [WEB-DL].mkv' },
        { label: 'Indexer', value: 'Nyaa.si' },
        { label: 'Size', value: '1.2 GB' },
      ]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Monkey D. Luffy and his pirate crew explore the Grand Line in search of the world's ultimate treasure.",
      detailUrl: 'https://www.thetvdb.com/series/one-piece',
    },
  },
  {
    id: 'sonarr-download',
    name: 'Sonarr - Download',
    description: 'Template for Sonarr download complete notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'The Last of Us',
      eventType: 'Download',
      actionLabel: 'Download Complete',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([
        { code: 'S02E05', name: 'Endure and Survive', airDate: '2025-02-09' },
        { code: 'S02E06', name: 'The Dam', airDate: '2025-02-16' },
      ]),
      releaseDetailsJSON: JSON.stringify([
        { label: 'Quality', value: '2160p WEB-DL Dolby Vision' },
        { label: 'Release Group', value: 'NTb' },
        { label: 'Size', value: '8.4 GB' },
      ]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Joel and Ellie arrive at the Colorado hospital, where the Fireflies' true plan is revealed, and the journey faces its most difficult choice.",
      detailUrl: 'https://www.thetvdb.com/series/the-last-of-us',
    },
  },
  {
    id: 'sonarr-upgrade',
    name: 'Sonarr - Upgrade',
    description: 'Template for Sonarr upgrade notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'The Last of Us',
      eventType: 'Upgrade',
      actionLabel: 'Upgrade',
      instanceName: 'sonarr-lab',
      downloadClient: 'qBittorrent · Auto',
      isUpgrade: 'Yes',
      episodeListJSON: JSON.stringify([{ code: 'S02E05', name: 'Endure and Survive', airDate: '2025-02-09' }]),
      releaseDetailsJSON: JSON.stringify([
        { label: 'Quality', value: '2160p REMUX HEVC HDR10+' },
        { label: 'Release Group', value: 'TERMiNAL' },
        { label: 'Size', value: '12.8 GB' },
      ]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: "Joel and Ellie arrive at the Colorado hospital, where the Fireflies' true plan is revealed, and the journey faces its most difficult choice.",
      detailUrl: 'https://www.thetvdb.com/series/the-last-of-us',
    },
  },
  {
    id: 'sonarr-rename',
    name: 'Sonarr - Rename',
    description: 'Template for Sonarr rename notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'Breaking Bad',
      eventType: 'Rename',
      actionLabel: 'Rename',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([{ code: 'S05E16', name: 'Felina', airDate: '2013-09-29' }]),
      releaseDetailsJSON: JSON.stringify([]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.',
      detailUrl: 'https://www.thetvdb.com/series/breaking-bad',
    },
  },
  {
    id: 'sonarr-episodefiledelete',
    name: 'Sonarr - Episode File Delete',
    description: 'Template for Sonarr episode file delete notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'Game of Thrones',
      eventType: 'EpisodeFileDelete',
      actionLabel: 'Delete File',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([{ code: 'S08E06', name: 'The Iron Throne', airDate: '2019-05-19' }]),
      releaseDetailsJSON: JSON.stringify([]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'Nine noble families fight for control over the lands of Westeros.',
      detailUrl: 'https://www.thetvdb.com/series/game-of-thrones',
    },
  },
  {
    id: 'sonarr-seriesdelete',
    name: 'Sonarr - Series Delete',
    description: 'Template for Sonarr series delete notifications',
    html: sonarrDefault,
    variables: [
      'seriesTitle',
      'eventType',
      'actionLabel',
      'instanceName',
      'downloadClient',
      'isUpgrade',
      'episodeListJSON',
      'releaseDetailsJSON',
      'coverImage',
      'synopsis',
      'detailUrl',
    ],
    defaultVariables: {
      seriesTitle: 'The Office',
      eventType: 'SeriesDelete',
      actionLabel: 'Delete Series',
      instanceName: 'sonarr-lab',
      downloadClient: '',
      isUpgrade: 'No',
      episodeListJSON: JSON.stringify([]),
      releaseDetailsJSON: JSON.stringify([]),
      coverImage: 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=960&q=80',
      synopsis: 'A mockumentary on a group of typical office workers.',
      detailUrl: 'https://www.thetvdb.com/series/the-office',
    },
  },
]
